### ISSUE TITLE
Questions Resource Pack

### ISSUE THREAD

**Issue by M1B4ND** [felixstaude/Emotes#1]
Hello, can you show an example of a texture pack. I've done everything as shown in your tutorial but it doesn't work on my end.

**Comment by felixstaude** [comment]
Yes of course, i'll take care of that today

**Comment by M1B4ND** [comment]
I made the texture pack with the structure you wrote. This tells me that the texture pack can't be taken into account by the game.

**Comment by felixstaude** [comment]
i came into the same issue, im working on it. You got any Errors in Console? Could you paste them in here if so?

**Comment by M1B4ND** [comment]
it looks like the texture pack structure has changed recently.

`Pack/assets/minecraft/textures/emotes.png` I don't think this is correct.
I'm not getting an error in the console, it's the game telling me that the pack can't be supported.

Whether it's the pack installed on the server or if I install the same pack on the player side.

**Comment by felixstaude** [comment]
i think in Pack/pack.mcmeta the pack_format should be 15 for 1.20.-1.20.1 and 18 for 1.20.2
i dont know much about texturepacks. I cant test it right now, but maybe you could 

https://minecraft.fandom.com/wiki/Pack_format

**Comment by M1B4ND** [comment]
I think that was the problem. Now it works. Thanks
![image](https://github.com/felixstaude/Emotes/assets/70129787/8566fdd9-da7b-4941-ba9f-efa236e424a3)
