### ISSUE TITLE
Compatibility with other message plugins

### ISSUE THREAD

**Issue by M1B4ND** [felixstaude/Emotes#3]
It seems that Emotes is not compatible with other message plugins. Like DiscordSRV in my case.

Hypothesis: it seems that Emotes cancels players' messages in order to resend them. Wouldn't it be better to modify player messages? So that other message plugins, such as DiscordSRV, can process them too.
I've been told it could be event.setMessage().

What do you think? Do you have the same problem yourself?

**Comment by felixstaude** [comment]
Yes it seems like its an issue of the onPlayerChatEvent, cause it gets cancelled and everyone gets a  message with the player.sendMessage() thing. I'll fix that later that day

**Comment by LEMIBANDDEXARI** [comment]
I don't think https://github.com/felixstaude/Emotes/pull/4 works. Because I've just tested it on my server and it doesn't seem to make any difference. I must have made a mistake somewhere.

**Comment by M1B4ND** [comment]
#4 This doesn't seem to be the right solution. Other plugins like DiscordSRV have access to messages now. But player messages are sent twice.
The message is displayed twice in-game, and only once on Discord
Screenshot of the in-game :
![image](https://github.com/felixstaude/Emotes/assets/70129787/1edc2c22-3a6f-4af0-b4cc-cfb157d50cc0)
Screenshot on Discord :
![image](https://github.com/felixstaude/Emotes/assets/70129787/b719f15f-acc3-4480-a5ea-88016f85d346)

**Comment by M1B4ND** [comment]
The problem is solved. I deleted the for loop on line 33.
https://github.com/felixstaude/Emotes/pull/4/commits/4ab9b9a5b952d40d02ad09168b3c0767588a38a1

These are new screenshots. They show that everything is working properly on my side.
in-game :
![image](https://github.com/felixstaude/Emotes/assets/70129787/2d29de9f-c024-420d-82cf-b8bf62e19224)
on Discord :
![image](https://github.com/felixstaude/Emotes/assets/70129787/700a77fd-69f0-45c9-b0fa-814120de6917)

**Comment by M1B4ND** [comment]
I don't know if you want to upgrade to Emotes-v1.1.1 or not. So I'll let you do it.

**Comment by felixstaude** [comment]
Yes, i will update as soon as im home from work. This looks right. Thank you!
